version: '3.3'
services:
    squid:
        image: sameersbn/squid:3.5.27-2
        ports:
            - 3128:3128
        volumes:
            - cache:/var/spool/squid
            - ./docker/squid/etc/squid/squid.conf:/etc/squid/squid.conf
        restart: always
volumes:
    cache:
